export_pipeline = """
nbs -> pts
nbs -> lib

nbs_test -> pts_test
nbs_test -> lib_test

nbs_dev -> pts_dev
nbs_dev -> lib_dev
"""
docs_cl='nbs'
docs_title="netrun"

readme_nb_path = "nbs/netrun/index.ipynb"

[cl.lib]
path="src/netrun"
format="module"

[cl.nbs]
path="nbs/netrun"
format="ipynb"

[cl.pts]
path="pts/netrun"
format="percent"


[cl.lib_test]
path="src/tests"
format="module"

[cl.nbs_test]
path="nbs/tests"
format="ipynb"

[cl.pts_test]
path="pts/tests"
format="percent"


[cl.nbs_dev]
path="nbs/dev"
format="ipynb"

[cl.pts_dev]
path="pts/dev"
format="percent"

[cl.lib_dev]
path="src/dev"
format="module"


[cl.examples]
path="nbs/examples"
format="ipynb"