export_pipeline = """
nbs -> pts
nbs -> lib

nbs_tests -> pts_tests
nbs_tests -> lib_tests

nbs_dev -> pts_dev
nbs_dev -> lib_dev

nbs_examples -> pts_examples
"""
docs_cl='nbs'
docs_title="netrun"

readme_nb_path = "nbs/netrun/index.ipynb"

[fill]
code_locations = ["nbs", "nbs_dev", "nbs_examples"]

[cl.lib]
path="src/netrun"
format="module"

[cl.nbs]
path="nbs/netrun"
format="ipynb"

[cl.pts]
path="pts/netrun"
format="percent"


[cl.lib_tests]
path="src/tests"
format="module"

[cl.nbs_tests]
path="nbs/tests"
format="ipynb"

[cl.pts_tests]
path="pts/tests"
format="percent"


[cl.nbs_dev]
path="nbs/dev"
format="ipynb"

[cl.pts_dev]
path="pts/dev"
format="percent"

[cl.lib_dev]
path="src/dev"
format="module"

[cl.nbs_examples]
path="nbs/examples"
format="ipynb"

[cl.pts_examples]
path="pts/examples"
format="percent"