export_pipeline = """
nbs -> pts
nbs -> lib
"""
docs_cl='nbs'
docs_title="netrun"

readme_nb_path = "nbs/netrun/index.ipynb"

[cl.lib]
path="src/netrun"
format="module"

[cl.nbs]
path="nbs/netrun"
format="ipynb"

[cl.pts]
path="pts/netrun"
format="percent"

[cl.lib_test]
path="src/tests"
format="module"

[cl.nbs_test]
path="nbs/tests"
format="ipynb"

[cl.pts_test]
path="pts/tests"
format="percent"

[cl.examples]
path="examples"
format="ipynb"