export_pipeline = """
nbs -> pts
nbs -> lib

nbs_examples -> pts_examples
nbs_examples -> lib_examples
"""

docs_cl='nbs'
docs_title="netrun"

readme_nb_path = "nbs/netrun/index.ipynb"

[cl.lib]
path="src/netrun"
format="module"

[cl.nbs]
path="nbs/netrun"
format="ipynb"

[cl.pts]
path="pts/netrun"
format="percent"

[cl.nbs_examples]
path="nbs/examples"
format="ipynb"

[cl.pts_examples]
path="pts/examples"
format="percent"

[cl.lib_examples]
path="src/examples"
format="module"